In [ ]:
from datasets import load_dataset
from datasets import DatasetDict

# load HuggingFaceM4/A-OKVQA@train and make a new dataset with only 10 rows
dataset = load_dataset("HuggingFaceM4/A-OKVQA")
dataset_train = dataset["train"].select(range(3000))
dataset_debug = dataset["train"].select(range(32))
dataset = DatasetDict({"train": dataset_train, "debug": dataset_debug})
print(dataset)
# push 
dataset.push_to_hub("Amasia-MLLM/A-OKVQA")

DatasetDict({
    train: Dataset({
        features: ['image', 'question_id', 'question', 'choices', 'correct_choice_idx', 'direct_answers', 'difficult_direct_answer', 'rationales'],
        num_rows: 32
    })
})


Uploading the dataset shards: 100%|██████████| 1/1 [00:01<00:00,  1.01s/it]


CommitInfo(commit_url='https://huggingface.co/datasets/Amasia-MLLM/A-OKVQA/commit/c4238fd560402b963875993d7c1d9c8941fb68a7', commit_message='Upload dataset', commit_description='', oid='c4238fd560402b963875993d7c1d9c8941fb68a7', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/Amasia-MLLM/A-OKVQA', endpoint='https://huggingface.co', repo_type='dataset', repo_id='Amasia-MLLM/A-OKVQA'), pr_revision=None, pr_num=None)

In [10]:
import torch
from tensordict import TensorDict

a = TensorDict({"a": torch.rand(2, 10), "b": torch.rand(2, 10)}, batch_size=2)
b = TensorDict({"a": torch.rand(2, 10), "b": torch.rand(2, 10)}, batch_size=2)

In [11]:
# Concatenate TensorDicts directly using the cat method
c = TensorDict.cat([a, b], dim=0)

In [12]:
c

TensorDict(
    fields={
        a: Tensor(shape=torch.Size([4, 10]), device=cpu, dtype=torch.float32, is_shared=False),
        b: Tensor(shape=torch.Size([4, 10]), device=cpu, dtype=torch.float32, is_shared=False)},
    batch_size=torch.Size([4]),
    device=None,
    is_shared=False)

In [13]:
a["a"]

tensor([[0.9447, 0.3040, 0.7937, 0.4449, 0.2798, 0.7888, 0.9491, 0.0281, 0.8462,
         0.6055],
        [0.7288, 0.2028, 0.6224, 0.8321, 0.5835, 0.1754, 0.5490, 0.7751, 0.4472,
         0.3362]])

In [14]:
b["a"]

tensor([[0.3437, 0.4464, 0.9242, 0.1525, 0.0605, 0.6676, 0.9656, 0.3910, 0.4433,
         0.8585],
        [0.9149, 0.7587, 0.0901, 0.7521, 0.7877, 0.9108, 0.7455, 0.3938, 0.7850,
         0.4449]])

In [15]:
c["a"]

tensor([[0.9447, 0.3040, 0.7937, 0.4449, 0.2798, 0.7888, 0.9491, 0.0281, 0.8462,
         0.6055],
        [0.7288, 0.2028, 0.6224, 0.8321, 0.5835, 0.1754, 0.5490, 0.7751, 0.4472,
         0.3362],
        [0.3437, 0.4464, 0.9242, 0.1525, 0.0605, 0.6676, 0.9656, 0.3910, 0.4433,
         0.8585],
        [0.9149, 0.7587, 0.0901, 0.7521, 0.7877, 0.9108, 0.7455, 0.3938, 0.7850,
         0.4449]])